#!/usr/bin/env ruby
# Put launch code here
$LOAD_PATH << 'lib'

require 'sinatra' # Has to be here for traditional approach
require 'config'

get '/' do
  # Doesn't load additional attributes otherwise
  @bills = Bill.all(order: [:date.desc])
  haml :bills
end

get '/category/:id' do |cat_id|
  @category = Category.get(cat_id)
  @bills = @category.bills
  haml :category_show do
    haml :bills
  end
end

get '/category/:id/edit' do |cat_id|
  @category = Category.get(cat_id)
  haml :category_edit do
    haml :_category_form
  end
end
